
language: groovy

jdk:
- oraclejdk11

sudo: required

notifications:
  email: false

install:
- ./gradlew -version
- sudo add-apt-repository ppa:wpilib/toolchain -y
- sudo apt-get update -q
- sudo apt-get install frc-toolchain -y

script:
- ./gradlew build publishToMavenLocal --stacktrace
